//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizacijskiToken
    {
        public int Id { get; set; }
        public string Vrijednost { get; set; }
        public int KorisnikId { get; set; }
        public System.DateTime VrijemeEvidentiranja { get; set; }
        public string IpAdresa { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
