//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casovi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Casovi()
        {
            this.Izostanci = new HashSet<Izostanci>();
            this.UceniciCasovi = new HashSet<UceniciCasovi>();
        }
    
        public int CasId { get; set; }
        public System.DateTime Datum { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public int NastavnikId { get; set; }
    
        public virtual Nastavnici Nastavnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izostanci> Izostanci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UceniciCasovi> UceniciCasovi { get; set; }
    }
}
