//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterijaliOcjene
    {
        public int MaterijaliOcjeneId { get; set; }
        public int MaterijalId { get; set; }
        public int UcenikId { get; set; }
        public int Ocjena { get; set; }
    
        public virtual Ucenici Korisnici_Ucenici { get; set; }
        public virtual Materijali Materijali { get; set; }
    }
}
