//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predaje()
        {
            this.UceniciOcjene = new HashSet<UceniciOcjene>();
        }
    
        public int PredajeId { get; set; }
        public int NastavnikId { get; set; }
        public int SkolskaGodinaId { get; set; }
        public int SmjerPredmetId { get; set; }
    
        public virtual Nastavnici Nastavnici { get; set; }
        public virtual SkolskeGodine SkolskeGodine { get; set; }
        public virtual SmjerPredmet SmjerPredmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UceniciOcjene> UceniciOcjene { get; set; }
    }
}
