//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razredi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Razredi()
        {
            this.UceniciRazredi = new HashSet<UceniciRazredi>();
        }
    
        public int RazredId { get; set; }
        public int RazredBrojcano { get; set; }
        public string Odjeljenje { get; set; }
        public string Oznaka { get; set; }
        public int SkolskaGodinaId { get; set; }
        public int NastavnikId { get; set; }
        public int SmjerId { get; set; }
    
        public virtual Nastavnici Nastavnici { get; set; }
        public virtual SkolskeGodine SkolskeGodine { get; set; }
        public virtual Smjerovi Smjerovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UceniciRazredi> UceniciRazredi { get; set; }
    }
}
