//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmjerPredmet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmjerPredmet()
        {
            this.Predaje = new HashSet<Predaje>();
        }
    
        public int SmjerPredmetId { get; set; }
        public int BrojCasova { get; set; }
        public int PredmetId { get; set; }
        public int SmjerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predaje> Predaje { get; set; }
        public virtual Predmeti Predmeti { get; set; }
        public virtual Smjerovi Smjerovi { get; set; }
    }
}
