//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UceniciOcjene
    {
        public int Id { get; set; }
        public int UcenikId { get; set; }
        public int PredajeId { get; set; }
        public int Vrijednost { get; set; }
        public System.DateTime Datum { get; set; }
        public string TipOcjene { get; set; }
        public string Napomena { get; set; }
    
        public virtual Predaje Predaje { get; set; }
        public virtual Ucenici Ucenici { get; set; }
    }
}
