//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UceniciCasovi
    {
        public int UcenikCasoviId { get; set; }
        public int UcenikId { get; set; }
        public int CasId { get; set; }
    
        public virtual Casovi Casovi { get; set; }
        public virtual Ucenici Ucenici { get; set; }
    }
}
