//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UceniciRazredi
    {
        public int UcenikRazrediId { get; set; }
        public int RedniBroj { get; set; }
        public string SkolskaGodina { get; set; }
        public int UcenikId { get; set; }
        public int RazredId { get; set; }
    
        public virtual Razredi Razredi { get; set; }
        public virtual Ucenici Ucenici { get; set; }
    }
}
