//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uloge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uloge()
        {
            this.KorisniciUloge = new HashSet<KorisniciUloge>();
        }
    
        public int UlogaId { get; set; }
        public string Naziv { get; set; }
        public bool SuperAdministrator { get; set; }
        public bool Administrator { get; set; }
        public bool Nastavnik { get; set; }
        public bool Ucenik { get; set; }
        public bool Roditelj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KorisniciUloge> KorisniciUloge { get; set; }
    }
}
