//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrednjeSkole_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrednjeSkole_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o nastavniku..
        /// </summary>
        internal static string add_nastavnik_succ {
            get {
                return ResourceManager.GetString("add_nastavnik_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali predmet..
        /// </summary>
        internal static string add_predmet_succ {
            get {
                return ResourceManager.GetString("add_predmet_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali razred..
        /// </summary>
        internal static string add_razred_succ {
            get {
                return ResourceManager.GetString("add_razred_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite razred (brojčano) !.
        /// </summary>
        internal static string add_razredBroj_req {
            get {
                return ResourceManager.GetString("add_razredBroj_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite odjeljenje (1 slovo) !.
        /// </summary>
        internal static string add_razredOdjeljenje_req {
            get {
                return ResourceManager.GetString("add_razredOdjeljenje_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite razrednika !.
        /// </summary>
        internal static string add_razredRazrednik_req {
            get {
                return ResourceManager.GetString("add_razredRazrednik_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite školsku godinu !.
        /// </summary>
        internal static string add_skGod_req {
            get {
                return ResourceManager.GetString("add_skGod_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali novu školsku godinu..
        /// </summary>
        internal static string add_skGod_succ {
            get {
                return ResourceManager.GetString("add_skGod_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o smjeru..
        /// </summary>
        internal static string add_smjer_succ {
            get {
                return ResourceManager.GetString("add_smjer_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o učeniku..
        /// </summary>
        internal static string add_ucenik_succ {
            get {
                return ResourceManager.GetString("add_ucenik_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o korisniku..
        /// </summary>
        internal static string add_usr_succ {
            get {
                return ResourceManager.GetString("add_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobe mlađe od 14 godina se ne mogu upisati u srednju školu..
        /// </summary>
        internal static string datum_err14 {
            get {
                return ResourceManager.GetString("datum_err14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobe starije od 20 godina se ne mogu upisati u srednju školu..
        /// </summary>
        internal static string datum_err20 {
            get {
                return ResourceManager.GetString("datum_err20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dodaj_sliku {
            get {
                object obj = ResourceManager.GetObject("dodaj_sliku", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o korisniku..
        /// </summary>
        internal static string edit_usr_succ {
            get {
                return ResourceManager.GetString("edit_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa je zauzeta..
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail nije u ispravnom formatu..
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite e-mail!.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite ime!.
        /// </summary>
        internal static string fname_err {
            get {
                return ResourceManager.GetString("fname_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG mora imati 13 karaktera..
        /// </summary>
        internal static string jmbg_err {
            get {
                return ResourceManager.GetString("jmbg_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite JMBG!.
        /// </summary>
        internal static string jmbg_req {
            get {
                return ResourceManager.GetString("jmbg_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite prezime!.
        /// </summary>
        internal static string lname_err {
            get {
                return ResourceManager.GetString("lname_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruka o uspjehu.
        /// </summary>
        internal static string msg_succ {
            get {
                return ResourceManager.GetString("msg_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite naziv !.
        /// </summary>
        internal static string naziv_req {
            get {
                return ResourceManager.GetString("naziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite opis !.
        /// </summary>
        internal static string opis_req {
            get {
                return ResourceManager.GetString("opis_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka treba da sadrži najmanje 6 karaktera (kombinacija slova i brojeva)..
        /// </summary>
        internal static string pass_err {
            get {
                return ResourceManager.GetString("pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite lozinku!.
        /// </summary>
        internal static string pass_req {
            get {
                return ResourceManager.GetString("pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite naziv predmeta !.
        /// </summary>
        internal static string predmet_naziv_req {
            get {
                return ResourceManager.GetString("predmet_naziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite oznaku predmeta !.
        /// </summary>
        internal static string predmet_oznaka_req {
            get {
                return ResourceManager.GetString("predmet_oznaka_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite najmanje jednu ulogu!.
        /// </summary>
        internal static string roles_req {
            get {
                return ResourceManager.GetString("roles_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite školsku godinu !.
        /// </summary>
        internal static string skGod_req {
            get {
                return ResourceManager.GetString("skGod_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite predmete koji se slušaju na smjeru !.
        /// </summary>
        internal static string smjer_predmet_req {
            get {
                return ResourceManager.GetString("smjer_predmet_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite smjer !.
        /// </summary>
        internal static string smjer_req {
            get {
                return ResourceManager.GetString("smjer_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string username_err {
            get {
                return ResourceManager.GetString("username_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite korisničko ime!.
        /// </summary>
        internal static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
